name: Create Artifact
on: [workflow_dispatch]

jobs:
  build-linux:
      name: linux-${{matrix.c_compiler}}
      runs-on: ubuntu-latest
      strategy:
          fail-fast: false
          matrix:
              include:
                  - c_compiler: gcc
                    cxx_compiler: g++
                  - c_compiler: clang
                    cxx_compiler: clang++
      steps:
          - name: Checkout shvav-8
            uses: actions/checkout@v2
            with:
                submodules: 'recursive'

          - name: Setup CMake
            uses: jwlawson/actions-setup-cmake@v1.8
            with:
                cmake-version: '3.16.x'

          - name: Setup Ninja
            uses: seanmiddleditch/gha-setup-ninja@v3

          - name: Install GLFW dependencies
            run: |
              sudo apt-get update
              sudo apt install xorg-dev

          - name: Build shvav-8
            env:
                CC: ${{matrix.c_compiler}}
                CXX: ${{matrix.cxx_compiler}}
            run: |
                mkdir build
                cd build
                cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release 
                cmake --build .

          - name: Install shvav-8
            run: |
                cd build
                mkdir install
                mkdir install/bin
                cp ./shvav-8 ./install/bin/shvav-8
                cp ../LICENSE ./install/LICENSE
                cp ../README.md ./install/README.md

          - name: Upload shvav-8 package
            uses: actions/upload-artifact@v2
            with:
                name: shvav-8-linux-${{matrix.c_compiler}}
                path: build/install/

  build-macos:
      name: macos-clang
      runs-on: macos-latest
      steps:
          - name: Checkout shvav-8
            uses: actions/checkout@v2
            with:
                submodules: 'recursive'

          - name: Setup CMake
            uses: jwlawson/actions-setup-cmake@v1.8
            with:
                cmake-version: '3.16.x'

          - name: Setup Ninja
            uses: seanmiddleditch/gha-setup-ninja@v3

          - name: Build shvav-8
            env:
                CC: clang
                CXX: clang++
            run: |
                mkdir build
                cd build
                cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release 
                cmake --build .

          - name: Install shvav-8
            run: |
                cd build
                cmake --install . --prefix ./install

          - name: Upload shvav-8 package
            uses: actions/upload-artifact@v2
            with:
                name: shvav-8-macos-clang
                path: build/install/


  build-windows:
      name: windows-${{matrix.arch}}-msvc
      runs-on: windows-latest
      strategy:
          fail-fast: false
          matrix:
              arch: [x64, x86]
      steps:
          - name: Checkout shvav-8
            uses: actions/checkout@v2
            with:
                submodules: 'recursive'

          - name: Setup MSVC
            uses: ilammy/msvc-dev-cmd@v1
            with:
                arch: ${{matrix.arch}}

          - name: Setup CMake
            uses: jwlawson/actions-setup-cmake@v1.8
            with:
                cmake-version: '3.16.x'

          - name: Setup Ninja
            uses: seanmiddleditch/gha-setup-ninja@v3

          - name: Build shvav-8
            env:
                CC: cl
                CXX: cl
            run: |
                mkdir build
                cd build
                cmake -G Ninja .. -DCMAKE_BUILD_TYPE=Release -DHAVE_LIBC=TRUE
                cmake --build .

          - name: Install shvav-8
            run: |
                cd build
                cmake --install . --prefix ./install

          - name: Upload shvav-8 package
            uses: actions/upload-artifact@v2
            with:
                name: shvav-8-windows-${{matrix.arch}}-msvc
                path: build/install/
